<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 2.1.1 
# *Data Wrangling and Munging with Pandas*

## Part 1: Wrangling Data

The term "data wrangling" is analogous to capturing wild horses and getting them into a fenced area; the horses are data and the fencing is your computer. The more common data wrangling tasks include:

- reading flat files
- reading Excel files
- downloading from web pages
  - csv
  - html
  - json

In [1]:
import numpy as np
import pandas as pd

*It is good practice to display the library version numbers for future reference:*

In [2]:
print('Numpy: ', np.__version__)
print('Pandas: ', pd.__version__)

Numpy:  1.18.5
Pandas:  1.0.5


### CSV Files

Below are three attempts to load the file "bikeshare.csv" into a DataFrame named `bikes`. Why are they wrong?

In [3]:
# wrong:
bikes = pd.read_table('bikeshare.csv', header = None)
print(bikes.head())
print()

                                                   0
0  instant,dteday,season,yr,mnth,hr,holiday,weekd...
1  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...
2  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...
3  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...
4  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...



In [4]:
# wrong:
bikes = pd.read_table('bikeshare.csv', header = None)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('bikeshare.csv', header = 1)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('dat/bikeshare.csv', header = 0)
print(bikes.head())

                                                   0
0  instant,dteday,season,yr,mnth,hr,holiday,weekd...
1  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...
2  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...
3  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...
4  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...

  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0,3,13,16
0  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...     
1  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...     
2  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...     
3  5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,...     
4  6,2011-01-01,1,0,1,5,0,6,0,2,0.24,0.2576,0.75,...     

  instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...                                                                   
1  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...                                        

?:

> Indented block


ANSWER: Case 1 treats headings as just another data row. Case 2 treats the 1st data row as the column header. Case 3 gets the header right (row 0), but reads each row as a single column (Nb. the other two make that same mistake). 

Load the file "bikeshare.csv" into a DataFrame named `bikes`, and confirm that it was loaded properly:

In [5]:
#ANSWER:
bikes = pd.read_table('bikeshare.csv', header = 0, sep = ',')
print(bikes.head())

   instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   
3        4  2011-01-01       1   0     1   3        0        6           0   
4        5  2011-01-01       1   0     1   4        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16  
1           1  0.22  0.2727  0.80        0.0       8          32   40  
2           1  0.22  0.2727  0.80        0.0       5          27   32  
3           1  0.24  0.2879  0.75        0.0       3          10   13  
4           1  0.24  0.2879  0.75        0.0       0           1    1  


Note that we could have used `read.csv()` above. When is `read_table()` necessary?

?:
ANSWER: When `sep` is not the comma character, or we need fine control that `read.csv()` does not provide.

Flat files can be full of surprises. Here are some issues to watch out for:

- separator character is something other than the comma
  - ";", "|", and tab are popular
- newline character is something other than what the O/S expects 
  - Tip: Don't hard-code the character codes for carriage returns, linefeeds, etc. Use Python's built-in representation instead (e.g. Python translates "\n" to the newline character and "\t" to the tab character on any O/S).
- truncated lines
  - if there are empty fields at the end of a line it is possible that their separators will be missing, resulting in a "jagged" file
- embedded commas or quotes
  - a free-text field containing embedded commas may split into separate fields on input
  - a free-text field containing embedded quotes may not parse correctly
- unescaped characters
  - the "\" character indicates a control code to Python, which will break the I/O
    - e.g. the substring "\u0123" will be interpreted as Unicode(0123) -- which may not be what the file creator intended
  - these may need to be fixed by loading whole strings and then parsing into a new data frame
  
Tip: Most issues can be delth with by correctly specifying the parameters of the function you use to load the file. Read the doco before reading the data!

### Reading Excel Files

In [6]:
from pandas import ExcelFile  # Nb. Need to install xlrd from conda (it does not automatically install with pandas)

In [7]:
df = pd.read_excel('Iris.xls', sheet_name = 'Data')
df

Species_No  Petal_width  Petal_length  Sepal_width  Sepal_length  \
0             1          0.2           1.4          3.5           5.1   
1             1          0.2           1.4          3.0           4.9   
2             1          0.2           1.3          3.2           4.7   
3             1          0.2           1.5          3.1           4.6   
4             1          0.2           1.4          3.6           5.0   
..          ...          ...           ...          ...           ...   
145           3          2.3           5.2          3.0           6.7   
146           3          1.9           5.0          2.5           6.3   
147           3          2.0           5.2          3.0           6.5   
148           3          2.3           5.4          3.4           6.2   
149           3          1.8           5.1          3.0           5.9   

    Species_name  
0         Setosa  
1         Setosa  
2         Setosa  
3         Setosa  
4         Setosa  
..           ...  
145    Verginica  
146    Verginica  
147    Verginica  
148    Verginica  
149    Verginica  

[150 rows x 6 columns]

So, this file appears to have an embedded table of aggregates on the same sheet as the raw data (a naughty but common practice amongst analysts).

It is usually better to load data correctly than to meddle with the source file or load it 'warts and all' and then try to parse it in code. The Pandas functions for reading files have parameters that provide the control we need. For ecxample, we could make multiple calls to `read_excel()`, using combinations of the `header`, `usecols`, `skiprows`, `nrows`, and `skipfooter` parameters to load one table at a time from a spreadsheet with multiple tables.

Load the above file without the unwanted columns:

In [8]:
#ANSWER
df = pd.read_excel('Iris.xls', sheet_name = 'Data', header = 0, usecols = [0, 1, 2, 3, 4])
df

Species_No  Petal_width  Petal_length  Sepal_width  Sepal_length
0             1          0.2           1.4          3.5           5.1
1             1          0.2           1.4          3.0           4.9
2             1          0.2           1.3          3.2           4.7
3             1          0.2           1.5          3.1           4.6
4             1          0.2           1.4          3.6           5.0
..          ...          ...           ...          ...           ...
145           3          2.3           5.2          3.0           6.7
146           3          1.9           5.0          2.5           6.3
147           3          2.0           5.2          3.0           6.5
148           3          2.3           5.4          3.4           6.2
149           3          1.8           5.1          3.0           5.9

[150 rows x 5 columns]

### Importing Data Directly from the Web

We usually want to store a local copy of a data file that we download from the Web, but when data retention is not a priority it is convenient to download the data directly into our running Python environment.

#### Importing Text Files from the Web

The web is the 'wild west' of data formats. However, we can usually expect good behaviour from files that are automatically generated by a service, such as the earthquake report:

In [9]:
df = pd.read_csv('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_hour.csv')
df.head()

time  latitude  longitude  depth  mag magType  nst  \
0  2021-05-05T06:21:25.246Z   38.2014  -117.7507    4.7  2.5      ml   18   

     gap   dmin     rms  ...                   updated  \
0  98.55  0.393  0.2878  ...  2021-05-05T06:44:09.692Z   

                      place        type horizontalError depthError  magError  \
0  37 km SE of Mina, Nevada  earthquake             NaN        0.7       0.5   

   magNst     status  locationSource magSource  
0      10  automatic              nn        nn  

[1 rows x 22 columns]

#### Importing HTML Files from the Web

Working with unstructured HTML files relies heavily on library functions. This one, however, is well-structured:

In [10]:
url = 'https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/'
df = pd.read_html(url)
df

[                         Bank NameBank           CityCity StateSt  CertCert  \
 0                    Almena State Bank             Almena      KS     15426   
 1           First City Bank of Florida  Fort Walton Beach      FL     16748   
 2                 The First State Bank      Barboursville      WV     14361   
 3                   Ericson State Bank            Ericson      NE     18265   
 4     City National Bank of New Jersey             Newark      NJ     21111   
 ..                                 ...                ...     ...       ...   
 558                 Superior Bank, FSB           Hinsdale      IL     32646   
 559                Malta National Bank              Malta      OH      6629   
 560    First Alliance Bank & Trust Co.         Manchester      NH     34264   
 561  National State Bank of Metropolis         Metropolis      IL      3815   
 562                   Bank of Honolulu           Honolulu      HI     21029   
 
                  Acquiring Institutio

In [11]:
df[0]

Bank NameBank           CityCity StateSt  CertCert  \
0                    Almena State Bank             Almena      KS     15426   
1           First City Bank of Florida  Fort Walton Beach      FL     16748   
2                 The First State Bank      Barboursville      WV     14361   
3                   Ericson State Bank            Ericson      NE     18265   
4     City National Bank of New Jersey             Newark      NJ     21111   
..                                 ...                ...     ...       ...   
558                 Superior Bank, FSB           Hinsdale      IL     32646   
559                Malta National Bank              Malta      OH      6629   
560    First Alliance Bank & Trust Co.         Manchester      NH     34264   
561  National State Bank of Metropolis         Metropolis      IL      3815   
562                   Bank of Honolulu           Honolulu      HI     21029   

                 Acquiring InstitutionAI Closing DateClosing  FundFund  
0                            Equity Bank    October 23, 2020     10538  
1              United Fidelity Bank, fsb    October 16, 2020     10537  
2                         MVB Bank, Inc.       April 3, 2020     10536  
3             Farmers and Merchants Bank   February 14, 2020     10535  
4                        Industrial Bank    November 1, 2019     10534  
..                                   ...                 ...       ...  
558                Superior Federal, FSB       July 27, 2001      6004  
559                    North Valley Bank         May 3, 2001      4648  
560  Southern New Hampshire Bank & Trust    February 2, 2001      4647  
561              Banterra Bank of Marion   December 14, 2000      4646  
562                   Bank of the Orient    October 13, 2000      4645  

[563 rows x 7 columns]

#### Importing XML Files from the Web

XML files are semi-structured, but you're at the mercy of the file creator. If every record has the same format it will be much easier, but practical applications often require a lot of custom code. Here is an example that includes a nice parser class: http://www.austintaylor.io/lxml/python/pandas/xml/dataframe/2016/07/08/convert-xml-to-pandas-dataframe/

#### Importing JSON Files from the Web

Like XML, JSON files are semi-structured and may require work to capture the schema into a dataframe. Here is a simple example: 

In [12]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/data.json'

# Load the first sheet of the JSON file into a data frame
df = pd.read_json(url, orient = 'columns')
df.head()

integer            datetime  category
0        5 2015-01-01 00:00:00         0
1        5 2015-01-01 00:00:01         0
2        9 2015-01-01 00:00:02         0
3        6 2015-01-01 00:00:03         0
4        6 2015-01-01 00:00:04         0

## Part 2: Data Munging

Data munging is manipulating data to get it into a form that we can start running analyses on (which usually means getting the data into a DataFrame). Before we get to this stage, we may need to remove headers or footers, transpose columns to rows, split wide data tables into long ones, and so on. (Nb. Excel files can be particularly troublesome, because users can format their data in mixed, complex shapes.) Essentially, we need to follow Hadley Wickham's guidelines for tidy datasets (http://vita.had.co.nz/papers/tidy-data.html):

The end goal of the cleaning data process:

- each variable should be in one column
- each observation should comprise one row
- each type of observational unit should form one table
- include key columns for linking multiple tables
- the top row contains (sensible) variable names
- in general, save data as one file per table


### Dataset Morphology

Once we have our dataset in a DataFrame (or Series, if our data is only 1-dimensional), we can start examining its size and content.

How many rows and columns are in `bikes`?

In [13]:
#ANSWER
bikes.shape

(17379, 17)

What are the column names in `bikes`?

In [14]:
#ANSWER
bikes.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

What are the data types of these columns?

In [15]:
#ANSWER
bikes.dtypes

instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

What is the (row) index for this DataFrame?

---



In [16]:
#ANSWER
bikes.index

RangeIndex(start=0, stop=17379, step=1)

https://www.dataquest.io/blog/python-json-tutorial/

## Slicing and Dicing

It is often preferable to refer to DataFrame columns by name, but there is more than one way to do this. 
Do `bikes['season']` and `bikes[['season']]` give the same object? Demonstrate:

In [17]:
#ANSWER
print(bikes['atemp'].head())
print(type(bikes['atemp']))
print(bikes[['atemp']].head())
print(type(bikes[['atemp']]))

0    0.2879
1    0.2727
2    0.2727
3    0.2879
4    0.2879
Name: atemp, dtype: float64
<class 'pandas.core.series.Series'>
    atemp
0  0.2879
1  0.2727
2  0.2727
3  0.2879
4  0.2879
<class 'pandas.core.frame.DataFrame'>


How would we use object notation to show the first 4 rows of `atemp`?

In [18]:
#ANSWER
print(bikes.atemp[:4])

0    0.2879
1    0.2727
2    0.2727
3    0.2879
Name: atemp, dtype: float64


Algorithms that loop over multiple columns often access DataFrame columns by index. However, none of the following work (try them out by uncommenting / removing the "#E: " ): 

In [19]:
bikes[[0]]
#E: bikes[0]
#E: bikes[0,0]
#E: bikes[[0,0]]

KeyError: "None of [Int64Index([0], dtype='int64')] are in the [columns]"

In [20]:
bikes[0]

KeyError: 0

In [21]:

bikes[0,0]


KeyError: (0, 0)

What is the correct way to access the 1st row of the DataFrame by its index?

In [22]:
#ANSWER
bikes[:1]

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16

What is the correct way to access the 2nd column of the DataFrame by its index?

In [23]:
#ANSWER
bikes.iloc[:, 1]

0        2011-01-01
1        2011-01-01
2        2011-01-01
3        2011-01-01
4        2011-01-01
            ...    
17374    2012-12-31
17375    2012-12-31
17376    2012-12-31
17377    2012-12-31
17378    2012-12-31
Name: dteday, Length: 17379, dtype: object

?..............................

## Handling Missing Values

What is the Pandas `isnull` function for? 

?
ANSWER: Detecting missing values.

We can apply `isnull` to the `bikes` DataFrame to show the result for every element:

In [24]:
bikes.isnull().head()

instant  dteday  season     yr   mnth     hr  holiday  weekday  workingday  \
0    False   False   False  False  False  False    False    False       False   
1    False   False   False  False  False  False    False    False       False   
2    False   False   False  False  False  False    False    False       False   
3    False   False   False  False  False  False    False    False       False   
4    False   False   False  False  False  False    False    False       False   

   weathersit   temp  atemp    hum  windspeed  casual  registered    cnt  
0       False  False  False  False      False   False       False  False  
1       False  False  False  False      False   False       False  False  
2       False  False  False  False      False   False       False  False  
3       False  False  False  False      False   False       False  False  
4       False  False  False  False      False   False       False  False

However, we usually start at a higher level. How many nulls are in the 'windspeed' column of `bikes` altogether?

In [25]:
#ANSWER
bikes['windspeed'].isnull().sum()

0

If this result were nonzero we would next want to find out which columns contained nulls. How can this be done in one line of code?

In [26]:
#ANSWER
bikes.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

What is the Numpy object `nan` used for? (Write a descriptive answer.)

?
ANSWER: Marking a data point as invalid.

Write (and verify) a function that performs scalar division with built-in handling of the edge case (i.e. return a value instead of just trapping the error):

In [27]:
#ANSWER
def divide(dividend, divisor):
    if divisor == 0:
        quotient = np.nan
    else:
        quotient = dividend / divisor
    return (quotient)

print(divide(1, 0))

nan


Apply the Pandas `isna` function to the following data objects:

In [28]:
x = 2.3
y = np.nan
print(x, y)

2.3 nan


In [29]:
#ANSWER
print(pd.isna(x), pd.isna(y))

False True


In [30]:
array = np.array([[1, np.nan, 3], [4, 5, np.nan]])
print(array)

[[ 1. nan  3.]
 [ 4.  5. nan]]


In [31]:
#ANSWER
print(pd.isna(array))

[[False  True False]
 [False False  True]]


How is the pandas I/O parameter `na_values` used?

? ANSWER: For converting specially coded strings to NaN on input (e.g. "###", "N/A", "NULL").

## Data Profiling

### Counts

When there are categorical variables in a dataset we will want to know how many possible values there are in each column. (Nb. If the dataset is a sample of a larger one, our sample may not capture all possible values of every categorical.)

How many (different) seasons are in `bikes`?

In [32]:
#ANSWER
bikes['season'].value_counts()

3    4496
2    4409
1    4242
4    4232
Name: season, dtype: int64

### Ranges

Print the range (min & max) of the `instant`, `dteday`, and `windspeed` columns: 

In [33]:
#ANSWER
print('instant:', bikes['instant'].min(), 'to', bikes['instant'].max())
print('dteday:', bikes['dteday'].min(), 'to', bikes['dteday'].max())
print('windspeed:', bikes['windspeed'].min(), 'to', bikes['windspeed'].max())

instant: 1 to 17379
dteday: 2011-01-01 to 2012-12-31
windspeed: 0.0 to 0.8507


Compute and print the overall minimum and maximum of the numeric data columns:

In [34]:
bikes_min, bikes_max = (min(bikes.min(numeric_only=True)), 
                        max(bikes.max(numeric_only=True)))
bikes_min, bikes_max

(0.0, 17379.0)

### Quantiles

Pandas makes computing quantiles easy. This is how to get the median of a Series:

In [35]:
bikes['atemp'].quantile(0.5)

0.4848

Of course, the `quantiles` method can take a tuple as its argument. Compute the 10th, 25th, 50th, 75th, and 90th percentiles in one line of code: 

In [36]:
#ANSWER
bikes['atemp'].quantile((0.1, 0.25, 0.5, 0.75, 0.9))

0.10    0.2424
0.25    0.3333
0.50    0.4848
0.75    0.6212
0.90    0.6970
Name: atemp, dtype: float64

### Cuts

Sometimes we want to split the sample not by the quantiles of the distribution but by the range of the data. Let's take a closer look at `atemp`:

In [37]:
type(bikes['atemp'])

pandas.core.series.Series

In [38]:
bikes.sample(5)

instant      dteday  season  yr  mnth  hr  holiday  weekday  \
765        766  2011-02-04       1   0     2   8        0        5   
10577    10578  2012-03-21       2   1     3  20        0        3   
14275    14276  2012-08-23       3   1     8   0        0        4   
13164    13165  2012-07-07       3   1     7  17        0        6   
4233      4234  2011-06-30       3   0     6   7        0        4   

       workingday  weathersit  temp   atemp   hum  windspeed  casual  \
765             1           1  0.14  0.1515  0.74     0.1343       3   
10577           1           1  0.56  0.5303  0.78     0.0896      76   
14275           1           1  0.64  0.5909  0.78     0.0000       9   
13164           0           1  0.96  0.8485  0.26     0.1343     103   
4233            1           1  0.62  0.6061  0.61     0.2239      29   

       registered  cnt  
765           217  220  
10577         298  374  
14275          51   60  
13164         176  279  
4233          291  320

Suppose we decide to sort these values into 4 bins of equal width, but we want to apply the resulting groups to the entire DataFrame. Basically, we need to add a row label that indcates which bin each sample belongs in. Let's call this label "atemp_level", and use the `cut` method to populate it:

In [39]:
atemp_level = pd.cut(bikes['atemp'], bins = 4)         

What type is `atemp_level`?

In [40]:
#ANSWER
print(type(atemp_level))

<class 'pandas.core.series.Series'>


Here is a random sample of `atemp_level`:

In [41]:
atemp_level.sample(5)          

14282       (0.5, 0.75]
13276       (0.5, 0.75]
708      (-0.001, 0.25]
9180        (0.25, 0.5]
10367       (0.25, 0.5]
Name: atemp, dtype: category
Categories (4, interval[float64]): [(-0.001, 0.25] < (0.25, 0.5] < (0.5, 0.75] < (0.75, 1.0]]

So, by default, `cut` produces labels that indicate the bin boundaries for each element in the series it was applied to. Usually, we will specify labels that are appropriate to the discretisation we are applying:

In [42]:
atemp_level = pd.cut(bikes['atemp'], bins = 4, labels = ["cool", "mild", "warm", "hot"])
atemp_level.sample(5)          

9399     mild
4381     warm
16760    cool
15612    warm
1583     mild
Name: atemp, dtype: category
Categories (4, object): [cool < mild < warm < hot]

Add the new `atemp_level` column into the `bikes` DataFrame and use it to count the number of "mild" `atemp` entries in `season` 2:

In [43]:
#ANSWER
bikes['atemp_level'] = atemp_level
bikes[(bikes.atemp_level == 'mild') & (bikes.season == 2)].season.count()  # Nb. could have used any column before count() in this case

1829

In [44]:
bikes[(bikes.atemp_level == 'mild') & (bikes.season == 2)].count() 

instant        1829
dteday         1829
season         1829
yr             1829
mnth           1829
hr             1829
holiday        1829
weekday        1829
workingday     1829
weathersit     1829
temp           1829
atemp          1829
hum            1829
windspeed      1829
casual         1829
registered     1829
cnt            1829
atemp_level    1829
dtype: int64

*Nb. The `atemp_level` variable we created is what the R language calls a "factor". Pandas has introduced a new data type called "category" that is similar to R's factors.*

# Synthetic Data

Sometimes we may want to generate test data, or we may need to initalise a series, matrix, or data frame for input to an algorithm. Numpy has several methods we can use for this.

Execute the following, then check the shape and content of each variable:

In [45]:
# Creating arrays with initial values
a = np.zeros((3))
b = np.ones((1,3))
c = np.random.randint(1,10,(2,3,4))   # randint(low, high, size)
d = np.arange(4)
e = np.array( [[1,2,3,4], [5,6,7,8]] )

In [46]:
print(a)
a.shape

[0. 0. 0.]


(3,)

In [47]:
print(b)
b.shape

[[1. 1. 1.]]


(1, 3)

In [48]:
print(c)
c.shape

[[[3 6 8 9]
  [7 4 9 6]
  [5 3 6 7]]

 [[5 5 8 7]
  [2 4 8 9]
  [9 1 7 2]]]


(2, 3, 4)

In [49]:
print(d)
d.shape

[0 1 2 3]


(4,)

In [50]:
print(e)
e.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

## Load Data

Load rock.csv and clean the dataset.

In [51]:
# Load CSV File
rock_csv = 'rock.csv'
rock = pd.read_csv(rock_csv)

In [52]:
rock.style.highlight_null(null_color='yellow')

## Check Column Names

Check column names and clean.

In [53]:
rock.columns

Index(['Song Clean', 'ARTIST CLEAN', 'Release Year', 'COMBINED', 'First?',
       'Year?', 'PlayCount', 'F*G'],
      dtype='object')

In [86]:
rock.head().style.highlight_null(null_color='yellow')

In [55]:
rock.tail()

Song Clean ARTIST CLEAN Release Year  \
2225                      She Loves My Automobile       ZZ Top          NaN   
2226                            Tube Snake Boogie       ZZ Top         1981   
2227                                         Tush       ZZ Top         1975   
2228                                   TV Dinners       ZZ Top         1983   
2229  WAITIN' FOR THE BUS/JESUS JUST LEFT CHICAGO       ZZ Top         1973   

                                               COMBINED  First?  Year?  \
2225                  She Loves My Automobile by ZZ Top       1      0   
2226                        Tube Snake Boogie by ZZ Top       1      1   
2227                                     Tush by ZZ Top       1      1   
2228                               TV Dinners by ZZ Top       1      1   
2229  WAITIN' FOR THE BUS/JESUS JUST LEFT CHICAGO by...       1      1   

      PlayCount  F*G  
2225          1    0  
2226         32   32  
2227        109  109  
2228          1    1  
2229          2    2

In [87]:
rock.sample(10).style.highlight_null(null_color='yellow')

In [57]:
rock.describe().T

count       mean        std  min  25%  50%   75%    max
First?     2230.0   1.000000   0.000000  1.0  1.0  1.0   1.0    1.0
Year?      2230.0   0.741256   0.438043  0.0  0.0  1.0   1.0    1.0
PlayCount  2230.0  16.872646  25.302972  0.0  1.0  4.0  21.0  142.0
F*G        2230.0  15.048430  25.288366  0.0  0.0  3.0  18.0  142.0

Columns names are not uniform.

    Uppercase, Lowercase > Lowercase
    Space > _
    ?, * > Remove

In [58]:
# Please clean the column names by creating a function for it
def clean_column_name(column_names):
    clean_column_names = []
    for c in column_names:
        c = c.lower().replace(' ', '_')
        c = c.lower().replace('*', '')
        c = c.lower().replace('?', '')
        clean_column_names.append(c)
        
    return clean_column_names

In [59]:
rock.columns = clean_column_name(rock.columns)

In [60]:
# check the column names again
rock.columns

Index(['song_clean', 'artist_clean', 'release_year', 'combined', 'first',
       'year', 'playcount', 'fg'],
      dtype='object')

# Replace Null Values With 0

Check 'release' column whether this column have any null value or not. Replace null value with 0.

In [61]:
# Check is there any nul values in any column
rock.isnull().sum()

song_clean        0
artist_clean      0
release_year    577
combined          0
first             0
year              0
playcount         0
fg                0
dtype: int64

- release year got 577 null values.

In [62]:
# Create a mask to find all rows with null values
null_mask = rock['release_year'].isnull()
rock.loc[null_mask, 'release_year'] = 0

In [63]:
# Check is there any nul values in any column
rock.isnull().sum()

song_clean      0
artist_clean    0
release_year    0
combined        0
first           0
year            0
playcount       0
fg              0
dtype: int64

In [64]:
# rock['Release Year'].fillna(0, inplace = True) # inplace stores the change in memory
# rock['Release Year'].isnull().sum()

# Check Datatypes of Dataset

Check datatypes of the dataset. Is there any column which should be int instead of object? Fix the column. 

In [65]:
# Check datatypes
rock.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2230 entries, 0 to 2229
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   song_clean    2230 non-null   object
 1   artist_clean  2230 non-null   object
 2   release_year  2230 non-null   object
 3   combined      2230 non-null   object
 4   first         2230 non-null   int64 
 5   year          2230 non-null   int64 
 6   playcount     2230 non-null   int64 
 7   fg            2230 non-null   int64 
dtypes: int64(4), object(4)
memory usage: 139.5+ KB


- release_year is object which should be integer

In [66]:
# Chekc values of release_year

rock['release_year'].value_counts()

0                577
1973             104
1977              83
1975              83
1970              81
1971              75
1969              72
1980              70
1978              64
1979              63
1967              61
1981              61
1983              60
1976              56
1982              54
1984              51
1972              50
1974              48
1968              46
1985              39
1987              39
1986              37
1991              34
1989              32
1966              30
1988              29
1965              28
1994              25
1990              22
1993              19
1964              14
1992              14
1999              13
1995              10
1963               9
1997               9
1996               9
2002               6
1998               6
2012               5
2005               5
2004               5
2001               4
2007               3
2008               3
2000               3
2011               3
1962         

- SONGFACTS.COM is not a valid release_year

In [67]:
# Create a mask to find all rows with SONGFACTS.COM
song_facts_mask = rock['release_year'] == 'SONGFACTS.COM'
rock.loc[song_facts_mask, 'release_year'] = np.NaN

In [68]:
# Convert release year to numeric
rock['release_year'] = pd.to_numeric(rock['release_year'])

In [69]:
# Check data types
rock.dtypes

song_clean       object
artist_clean     object
release_year    float64
combined         object
first             int64
year              int64
playcount         int64
fg                int64
dtype: object

In [70]:
# rock['Release Year'] = rock['Release Year'].replace("SONGFACTS.COM", 0)
# rock['release_year'] = pd.to_numeric(rock['release_year'])

# Check Min, Max of Each Column

*   List item
*   List item



Is there any illogical value in any column? How can we fix that?

In [71]:
def check_min_max(df):
    # Check min, max of each column
    print(df.describe().T[['min', 'max']])

In [72]:
check_min_max(rock)

              min     max
release_year  0.0  2014.0
first         1.0     1.0
year          0.0     1.0
playcount     0.0   142.0
fg            0.0   142.0


- Minimum Value of release year is 0, which is wrong

In [73]:
# Create a mask to find all rows with 0
song_facts_mask = rock['release_year'] == 0
rock.loc[song_facts_mask, 'release_year'] = np.NaN

In [74]:
check_min_max(rock)

                 min     max
release_year  1071.0  2014.0
first            1.0     1.0
year             0.0     1.0
playcount        0.0   142.0
fg               0.0   142.0


*italicized text*- Still minimum value is 1071. It's very unlikely there were any rock song in that year!

In [75]:
# Create a mask to find all rows with 1071
song_facts_mask = rock['release_year'] == 1071
rock.loc[song_facts_mask, 'release_year'] = np.NaN

In [76]:
check_min_max(rock)

                 min     max
release_year  1955.0  2014.0
first            1.0     1.0
year             0.0     1.0
playcount        0.0   142.0
fg               0.0   142.0


# Write Some Functions

## Write a function that will take a row of a DataFrame and print out the song, artist, and whether or not the release date is < 1970

In [77]:
rock.dtypes

song_clean       object
artist_clean     object
release_year    float64
combined         object
first             int64
year              int64
playcount         int64
fg                int64
dtype: object

In [78]:
def check_song(row):
    print('Song: ', row['song_clean'])
    print('Artist: ', row['artist_clean'])
    print('Released before 1970: ', row['release_year'] < 1970)
    print('\n')

In [79]:
# Check the first row of the dataset
rock.iloc[0]

song_clean                     Caught Up in You
artist_clean                        .38 Special
release_year                               1982
combined        Caught Up in You by .38 Special
first                                         1
year                                          1
playcount                                    82
fg                                           82
Name: 0, dtype: object

In [80]:
# Use your newly created function and Check any row using index
check_song(rock.iloc[0])

Song:  Caught Up in You
Artist:  .38 Special
Released before 1970:  False




In [81]:
# Check first five rows
rock.head(5).apply(check_song, axis=1)

Song:  Caught Up in You
Artist:  .38 Special
Released before 1970:  False


Song:  Fantasy Girl
Artist:  .38 Special
Released before 1970:  False


Song:  Hold On Loosely
Artist:  .38 Special
Released before 1970:  False


Song:  Rockin' Into the Night
Artist:  .38 Special
Released before 1970:  False


Song:  Art For Arts Sake
Artist:  10cc
Released before 1970:  False




0    None
1    None
2    None
3    None
4    None
dtype: object

## Write a function that converts cells in a DataFrame column to float and if error, otherwise replaces them with np.nan

In [82]:
def convert_to_float(column):
    column = pd.to_numeric(column, errors='coerce')
    return column

## Apply these functions to your dataset

In [83]:
rock.apply(convert_to_float)

song_clean  artist_clean  release_year  combined  first  year  \
0            NaN           NaN        1982.0       NaN      1     1   
1            NaN           NaN           NaN       NaN      1     0   
2            NaN           NaN        1981.0       NaN      1     1   
3            NaN           NaN        1980.0       NaN      1     1   
4            NaN           NaN        1975.0       NaN      1     1   
...          ...           ...           ...       ...    ...   ...   
2225         NaN           NaN           NaN       NaN      1     0   
2226         NaN           NaN        1981.0       NaN      1     1   
2227         NaN           NaN        1975.0       NaN      1     1   
2228         NaN           NaN        1983.0       NaN      1     1   
2229         NaN           NaN        1973.0       NaN      1     1   

      playcount   fg  
0            82   82  
1             3    0  
2            85   85  
3            18   18  
4             1    1  
...         ...  ...  
2225          1    0  
2226         32   32  
2227        109  109  
2228          1    1  
2229          2    2  

[2230 rows x 8 columns]

Describe the new float-only DataFrame.


In [84]:
# Describe Dataframe. All columns are float.
rock.describe().T

count         mean        std     min     25%     50%     75%  \
release_year  1651.0  1978.569352   9.309780  1955.0  1971.0  1977.0  1984.0   
first         2230.0     1.000000   0.000000     1.0     1.0     1.0     1.0   
year          2230.0     0.741256   0.438043     0.0     0.0     1.0     1.0   
playcount     2230.0    16.872646  25.302972     0.0     1.0     4.0    21.0   
fg            2230.0    15.048430  25.288366     0.0     0.0     3.0    18.0   

                 max  
release_year  2014.0  
first            1.0  
year             1.0  
playcount      142.0  
fg             142.0



> 
>
>






---



---



> > > > > > > > > © 2021 Institute of Data


---



---



